### ISSUE TITLE
Compliance Checklist for 1.0 Release

### ISSUE THREAD

**Issue by samsp-msft** [CoreWCF/CoreWCF#552]
When we release software at Microsoft, we have a compliance checklist that needs to be completed. As a community project, CoreWCF doesn't fall under the scope of 1CS, but we should follow a similar process. The following checklist is based on what would be done internally.

- [ ]	Global Readiness for Spring 2022 of CoreWCF	
	- [ ]	Run PoliCheck, Review and Address Results
	- [ ]	Review New Product, Feature and Service Names
	- [ ]	Ensure Language Availability
	- [ ]	Ensure Compliance with National Language Laws
	- [ ]	Ensure Product is Localizable
- [ ]	Global Trade for Spring 2022 of CoreWCF	
	- [ ]	Export Controls Compliance and Classification
- [ ]	License Terms for Spring 2022 of CoreWCF	
	- [ ]	Apply Correct License for an Open Source Software Release
- [ ]	Open Source License for Spring 2022 of CoreWCF	
	- [ ]	Register and scan all OSS components for security requirements
	- [ ]	Include 3rd-party licenses in a TPN
- [ ]	Privacy for Spring 2022 of CoreWCF	
	- [ ]	Complete a Privacy Review in the Privacy Manager portal
- [ ]	Security (DevDiv) for Spring 2022 of CoreWCF	
	- [ ]	Complete Android and Linux specific activities * S AZ L
	- [ ]	Provide account lockout after repeated failed logon attempts * S L
	- [ ]	Verify applications have no hard dependencies on Kerberos or NTLM * S AZ L
	- [ ]	Verify that applications or functionality uses the least privilege principle * S L AZ
	- [ ]	Ensure proper usage of symmetric block ciphers, key lengths, and initialization vectors * S
	- [ ]	Use only approved crypto libraries for the supported platform - S AZ L
	- [ ]	Ensure appropriate transmitted data is encrypted and integrity protected
	- [ ]	Verify you are using only approved asymmetric algorithms, key lengths, and padding modes - SP
	- [ ]	Verify you are using only approved key derivation functions when deriving cryptographic keys from asymmetric key agreement algorithms or user-provided input - S
	- [ ]	Use only approved random number generators - S
	- [ ]	Use only approved methods to secure secret data prior to storage * SO L
	- [ ]	Use only approved MAC crypto algorithms - S
	- [ ]	Use only approved cryptographic hash functions - SP AZ L
	- [ ]	Encrypt customer and state data at-rest
	- [ ]	Verify all engineering team members complete security training annually * SO L
	- [ ]	z Verify all certificates comply with the minimum certificate profile - P
	- [ ]	All files that can be signed must be signed, ensure you're complying with File and Code signing guidelines
	- [ ]	Verify the configuration of security event logging for apps and services, and ensure logs are stored appropriately. * SOP AZ L
	- [ ]	Incorporate Third-Party Component Licensing Security Requirements in all Contracts * S
	- [ ]	Use minimum compiler and toolchain versions and set appropriate switches
	- [ ]	Author applications in a secure manner that minimizes capabilities of hosted web content - S
	- [ ]	Use only safe deserializers in functions that may process untrusted data - S AZ L
	- [ ]	Think like an attacker: Threat model all features or functionality in your service or product for each release or at least annually
	- [ ]	Manage your security bugs properly * S L AZ
	- [ ]	User-controllable data must be filtered before use
	- [ ]	Verify that Applications and dynamic-link libraries (DLLs) load DLLs and EXEs securely * S L
	- [ ]	Ensure that anti-malware scanning occurs on all product releases
	- [ ]	Check-ins must be authorized and performed via authorized Microsoft individual user accounts 
	- [ ]	Assess security of all open source software components used within your product or service 
	- [ ]	Verify that sensitive data is not accidentally disclosed * S L
	- [ ]	Ensure secure configuration guidance is available to customers * S L
	- [ ]	Client products must use an approved update distribution mechanism to deliver security updates to users * S L
	- [ ]	Implement secure logout and session management mechanisms - S
	- [ ]	Use separate model binding classes or binding filter lists to prevent MVC mass assignment vulnerabilities * S L
	- [ ]	Implement Secrets and Certificate Management best practices * SOP AZ L
	- [ ]	Run static code analysis tools, and file and fix bugs for identified security issues
	- [ ]	External web resources must be loaded from an approved source locations like a Microsoft operated URL 
	- [ ]	Applications and services must have an explicit approval and authorization mechanism * S L
	- [ ]	Applications must use the enterprise authentication platforms * S L
	- [ ]	Verify cryptographic algorithm parameters are stored with persisted encrypted data - S
	- [ ]	Implement crypto agility
	- [ ]	Limit symmetric cryptographic key lifetimes to a maximum of three years - S
	- [ ]	All data in transit and all HTTP-based network traffic must be encrypted, including SQL connections
	- [ ]	Security Response Plan must be complete and up to date for each product or service
	- [ ]	Passwords allowed by application must meet Microsoft requirements
	- [ ]	Inventory of all certificates must be maintained
	- [ ]	Validate File Access and Upload Paths
	- [ ]	Applications must not configure platforms to trust new root certificates
	- [ ]	Cryptographic errors must not be disclosed
	- [ ]	Default and test secrets must be changed
	- [ ]	Handle security interrupts for client authentication appropriately 
	- [ ]	Secrets must meet requirements
	- [ ]	XML Entity Resolution must be hardened or disabled
	- [ ]	Private symbols for all publicly released products must be available to MSRC engineering
	- [ ]	Push notifications must be handled in a secure fashion
	- [ ]	Security details must not be exposed in error messages
- [ ]	Source Code Archive for Spring 2022 of CoreWCF	
	- [ ]	Archive Source Code
